export const extra = {
  ru: {
    map_fail: 'Не удалось запустить карту. Проверьте, что в браузере включён WebGL и есть доступ к tiles.openfreemap.org.', err_title: 'Что-то пошло не так на этой странице.', model_off: 'Модель обнаружения не загружена, поэтому анализ временно недоступен. Администратору: положите веса в backend/weights/yolov8x-fire.pt или задайте YOLO_WEIGHTS_URL.',
    tab_upload: 'Загрузка', tab_queue: 'Очередь', tab_hot: 'Очаги', tab_new: 'Новый', open_map: 'На карте', peek: 'Список очагов', skip: 'К основному содержимому', close: 'Закрыть',
    nav_home: 'Главная', nav_analyze: 'Анализ', nav_map: 'Карта', nav_dash: 'Панель',
    hero_badge: 'Спутниковый и дронный ИИ-мониторинг', hero_title: 'Интеллектуальный мониторинг лесных пожаров',
    hero_a: 'В 2023 году Россия потеряла более ', hero_stat: '4,3 млн гектаров',
    hero_b: ' леса из-за пожаров — рекордный показатель. КЕДР использует анализ на основе ИИ для обнаружения огня и дыма в реальном времени, помогая предотвратить катастрофические потери.',
    cta: 'Попробовать анализ', core: 'Ядро YOLOv8', latency: 'Отклик < 3.0с',
    f_label: 'Технические возможности', f_title: 'Возможности сервиса',
    f: [['Анализ изображений', 'Нейросеть YOLOv8 распознаёт огонь и дым на фото и видео за секунды.'],
        ['Карта России', 'Мониторинг очагов пожаров по всей стране с поиском по любому населённому пункту.'],
        ['Точность 98%', 'Двухступенчатая проверка лесничим минимизирует ложные срабатывания.'],
        ['Мгновенные оповещения', 'Критические очаги сразу приходят диспетчерам МЧС с расчётом эвакуации.']],
    p_label: 'Системный конвейер', p_title: 'Как это работает',
    p: [['Загрузка', 'Загрузите фото или видео, GPS берётся из EXIF'], ['Обработка', 'Кадры выбираются раз в секунду'],
        ['ИИ-анализ', 'Нейросеть ищет огонь и дым'], ['Результат', 'Уровень риска, координаты и план эвакуации']],
    end_title: 'Готовы защитить наши леса?', end_text: 'Загрузите снимок, и ИИ КЕДР мгновенно его проанализирует. Регистрация не требуется.',
    foot_text: 'Платформа раннего обнаружения лесных пожаров и дыма на основе нейросети.', foot_nav: 'Навигация',
    foot_ver: 'Версия ядра', rights: 'Все права защищены', n1: 'Возможности', n2: 'Как это работает', n3: 'Контакты',
    analyze_h: 'Анализ снимка', analyze_p: 'Загрузите фото или видео. Если в файле есть GPS, точка появится на карте автоматически.',
    tiers: 'Уверенность ИИ: ниже 40% — чисто; 40–80% — проверяет лесничий; от 80% — критическая тревога для МЧС.',
    search_ph: 'Поиск города или посёлка в России', source_ai: 'ИИ', source_manual: 'Ручной ввод диспетчера',
    wx_off: 'Метеоданные недоступны — зона показана без учёта ветра.', retry: 'Обновить',
    no_places: 'В зоне угрозы населённых пунктов не найдено.', circle_note: 'Ветер неизвестен: круг ~5–6 км (P₀ и влажность).',
    src_osm: 'Населённые пункты: OpenStreetMap', src_local: 'Населённые пункты: локальная база (OSM недоступен)',
    evac_dir: 'Эвакуация', na: 'н/д', pick_hint: 'Кликните по карте или найдите город, чтобы выбрать точку.',
    need_login: 'Для этой панели нужен вход.', legend: 'Легенда',
    tab_map: 'На карте', delete: 'Удалить', delete_confirm: 'Удалить инцидент без возможности восстановления?',
    register: 'Регистрация', register_submit: 'Создать аккаунт', full_name: 'Имя', password_rules: 'Минимум 8 символов, буква и цифра. Подтверждение почты не требуется.',
    manual_sub: 'Точка на карте + фото. Нейросеть не определяет GPS — только огонь/дым.',
    step_place: '1. Место пожара', manual_photo_req: 'Фото очага (обязательно)', manual_photo_opt: 'Фото для проверки (необязательно)',
    manual_drop: 'Выберите файл', manual_forester_note: 'При уверенности 40–80% — очередь лесничего; при сомнениях — подтверждение МЧС.',
    loc_how_title: 'Откуда координаты?', loc_how_body: 'YOLO видит огонь/дым, не направление камеры. GPS — из EXIF, устройства, поиска населённого пункта или точки на карте.',
    loc_search: 'Населённый пункт', loc_note: 'Уточнение', loc_note_ph: 'Например: 2 км севернее…',
    loc_required: 'Укажите место', loc_after: 'Нет GPS — укажите место для карты.', no_gps: 'Нет координат — уточните место.',
    city_panel: 'Город', city_loading: 'Загрузка…', city_infra: 'Инфраструктура рядом',
    city_infra_empty: 'В радиусе 12 км в OSM объектов не найдено.', city_infra_offline: 'Сервис OSM недоступен — не удалось получить список объектов. Попробуйте позже.',
    src_osm_infra: 'OpenStreetMap / Overpass',
    infra_partial: 'Часть категорий недоступна — Overpass вернул не всё',
    infra_hosp: 'Больница', infra_clinic: 'Поликлиника', infra_fire: 'Пожарная часть', infra_other: 'Объект',
    tab_all: 'Все', tab_review: 'Спорные',
    gps_EXIF: 'GPS: EXIF', gps_DEVICE: 'GPS: устройство', gps_MANUAL: 'GPS: вручную', gps_NONE: 'GPS: нет',
    fix_location: 'Уточнить место', save_location: 'Сохранить место', lat_label: 'Широта', lon_label: 'Долгота',
    pick_action: 'Указать на карте', map_sat: 'Спутник', map_map: 'Схема',
    infra_ambulance: 'Скорая', infra_police: 'Полиция', infra_school: 'Школа', infra_kindergarten: 'Детский сад',
    infra_pharmacy: 'Аптека', infra_shelter: 'Укрытие', infra_water: 'Водозабор', infra_power: 'Энергообъект',
    infra_government: 'Госучреждение', infra_industrial: 'Промзона',
    infra_nuclear: 'АЭС', infra_hydro_dam: 'ГЭС', infra_refinery: 'НПЗ', infra_chemical: 'Химзавод',
    infra_airport: 'Аэродром', infra_power_plant: 'Электростанция', infra_substation: 'Подстанция', infra_helipad: 'Вертодром',
    verdict_title: '3. Решение диспетчера', verdict_hint: 'Нейросеть не уверена — подтвердите пожар или поднимите критическую тревогу.',
    verdict_confirm: 'Обычный пожар', verdict_critical: 'Критическая тревога',
  },
  en: {
    map_fail: 'The map could not start. Check that WebGL is enabled and tiles.openfreemap.org is reachable.', err_title: 'Something went wrong on this page.', model_off: 'The detection model is not loaded, so analysis is unavailable. Admin: put weights at backend/weights/yolov8x-fire.pt or set YOLO_WEIGHTS_URL.',
    tab_upload: 'Upload', tab_queue: 'Queue', tab_hot: 'Hotspots', tab_new: 'New', open_map: 'On map', peek: 'Hotspot list', skip: 'Skip to main content', close: 'Close',
    nav_home: 'Home', nav_analyze: 'Analysis', nav_map: 'Map', nav_dash: 'Dashboard',
    hero_badge: 'Satellite & drone AI monitoring', hero_title: 'Intelligent forest fire monitoring',
    hero_a: 'In 2023 Russia lost over ', hero_stat: '4.3 million hectares',
    hero_b: ' of forest to fires — a record. KEDR uses AI to detect fire and smoke in real time and help prevent catastrophic losses.',
    cta: 'Try the analysis', core: 'YOLOv8 core', latency: 'Latency < 3.0s',
    f_label: 'Technical capabilities', f_title: 'Service features',
    f: [['Image analysis', 'YOLOv8 detects fire and smoke in photos and video within seconds.'],
        ['Map of Russia', 'Nationwide fire monitoring with search for any settlement.'],
        ['98% accuracy', 'Two-step forester review minimizes false alarms.'],
        ['Instant alerts', 'Critical fires go straight to MCHS dispatchers with an evacuation estimate.']],
    p_label: 'System pipeline', p_title: 'How it works',
    p: [['Upload', 'Upload a photo or video; GPS is read from EXIF'], ['Processing', 'Frames are sampled once per second'],
        ['AI analysis', 'The network looks for fire and smoke'], ['Result', 'Risk level, coordinates and evacuation plan']],
    end_title: 'Ready to protect our forests?', end_text: 'Upload an image and KEDR AI analyzes it instantly. No registration required.',
    foot_text: 'Neural-network platform for early detection of forest fires and smoke.', foot_nav: 'Navigation',
    foot_ver: 'Core version', rights: 'All rights reserved', n1: 'Features', n2: 'How it works', n3: 'Contacts',
    analyze_h: 'Image analysis', analyze_p: 'Upload a photo or video. If the file has GPS data, the point appears on the map automatically.',
    tiers: 'AI confidence: below 40% — clear; 40–80% — forester review; 80%+ — critical alert to MCHS.',
    search_ph: 'Search any city or village in Russia', source_ai: 'AI', source_manual: 'Dispatcher manual entry',
    wx_off: 'Weather data unavailable — zone shown without wind.', retry: 'Refresh',
    no_places: 'No settlements found in the threat zone.', circle_note: 'Wind unknown: ~5–6 km circle (P₀ and humidity).',
    src_osm: 'Settlements: OpenStreetMap', src_local: 'Settlements: local database (OSM unreachable)',
    evac_dir: 'Evacuate', na: 'n/a', pick_hint: 'Click the map or search for a city to pick a point.',
    need_login: 'Sign in to open this dashboard.', legend: 'Legend',
    tab_map: 'On map', delete: 'Delete', delete_confirm: 'Delete this incident permanently?',
    register: 'Sign up', register_submit: 'Create account', full_name: 'Name', password_rules: 'Min 8 chars with a letter and digit. No email verification.',
    manual_sub: 'Map point + photo. The model detects fire/smoke, not GPS.',
    step_place: '1. Fire location', manual_photo_req: 'Fire photo (required)', manual_photo_opt: 'Photo (optional)',
    manual_drop: 'Choose a file', manual_forester_note: 'AI 40–80% → forester queue; uncertain cases need MCHS.',
    loc_how_title: 'Where do coordinates come from?', loc_how_body: 'YOLO sees fire/smoke, not camera bearing. GPS from EXIF, device, settlement search, or map.',
    loc_search: 'Settlement', loc_note: 'Location note', loc_note_ph: 'e.g. 2 km north…',
    loc_required: 'Set a location', loc_after: 'No GPS — set location for the map.', no_gps: 'No coordinates yet.',
    city_panel: 'City', city_loading: 'Loading…', city_infra: 'Nearby infrastructure',
    city_infra_empty: 'No OSM facilities within 12 km.', city_infra_offline: 'OSM service unavailable — could not fetch facilities. Please retry.',
    src_osm_infra: 'OpenStreetMap / Overpass',
    infra_partial: 'Some categories unavailable — Overpass returned partial data',
    infra_hosp: 'Hospital', infra_clinic: 'Clinic', infra_fire: 'Fire station', infra_other: 'Facility',
    tab_all: 'All', tab_review: 'Uncertain',
    gps_EXIF: 'GPS: EXIF', gps_DEVICE: 'GPS: device', gps_MANUAL: 'GPS: manual', gps_NONE: 'GPS: none',
    fix_location: 'Fix location', save_location: 'Save location', lat_label: 'Latitude', lon_label: 'Longitude',
    pick_action: 'Pick on map', map_sat: 'Satellite', map_map: 'Map',
    infra_ambulance: 'Ambulance', infra_police: 'Police', infra_school: 'School', infra_kindergarten: 'Kindergarten',
    infra_pharmacy: 'Pharmacy', infra_shelter: 'Shelter', infra_water: 'Water intake', infra_power: 'Power facility',
    infra_government: 'Government', infra_industrial: 'Industrial',
    infra_nuclear: 'Nuclear plant', infra_hydro_dam: 'Hydro dam', infra_refinery: 'Oil refinery', infra_chemical: 'Chemical plant',
    infra_airport: 'Airport', infra_power_plant: 'Power plant', infra_substation: 'Substation', infra_helipad: 'Helipad',
    verdict_title: '3. Dispatcher decision', verdict_hint: 'The model is unsure — confirm the fire or raise a critical alert.',
    verdict_confirm: 'Usual fire', verdict_critical: 'Critical alert',
  },
}
